from .random_agent import RandomAgent
from .human_agent import HumanAgent
from .student_agent import StudentAgent
from .gpt_greedy_corners_agent import StudentAgent
from .agent0 import Agent0
from .agent1 import Agent1
from .ab_agent import AB_Agent
from .minimaxAB_agent import ThirdAgent
from .ab_mo_agent import AB_MO_Agent
from .ab_mo_t import AB_MO_T
from .mtc_ab_minmax import MTC_AB_MINMAX
from .MTCnotMonaco import MTC_NOT_MONACO
from .beaver import Beaver

from agents.extra.adv import ADV_Agent
from agents.extra.adv3 import ADV_Agent3
from agents.extra.adv4 import Adv4
from agents.extra.adv5 import ADV5
from agents.extra.adv6 import ADV6
from agents.extra.adv7 import ADV7
from agents.extra.adv8 import ADV8
from agents.extra.adv9 import ADV9
from agents.Beaver_test import BeaverTest
